#!/usr/bin/env node
/**
 * Wire-shape baseline refresher.
 *
 * Walks the same comparison the validator does and writes the result
 * to tests/fixtures/wire-shape-baseline.json. Use when a SHA bump or
 * deliberate burndown changes the expected drift set.
 *
 * Usage:
 *   node scripts/wire-shape/refresh.js <specs_dir> [--sha <SHA>]
 *
 * If --sha is omitted, attempts `git -C <specs_dir> rev-parse HEAD`.
 * Exits non-zero rather than write a baseline with empty SHA.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const {
  extractInterfaces,
  loadSchemas,
  computeDrift,
  writeBaseline,
  BASELINE_PATH,
  WIRE_BOUND,
} = require('./lib.cjs');

function gitHeadSha(specsDir) {
  try {
    const out = execFileSync('git', ['-C', specsDir, 'rev-parse', 'HEAD'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    });
    return out.trim();
  } catch {
    return '';
  }
}

function main() {
  const args = process.argv.slice(2);
  const specsDir = args[0];
  if (!specsDir) {
    console.error('usage: node scripts/wire-shape/refresh.js <specs_dir> [--sha <SHA>]');
    process.exit(2);
  }
  if (!fs.existsSync(specsDir) || !fs.statSync(specsDir).isDirectory()) {
    console.error(`error: ${specsDir} is not a directory`);
    process.exit(2);
  }

  let sha = '';
  for (let i = 1; i < args.length; i++) {
    if (args[i] === '--sha') sha = args[++i] || '';
  }
  if (!sha) sha = gitHeadSha(specsDir);
  if (!sha) {
    console.error(
      'error: could not determine OpenAPI specs commit SHA. Either run against a specs_dir inside a git checkout of getaxonflow/axonflow, or pass --sha <commit-sha> explicitly. An empty SHA would poison the baseline and fail the next CI run.',
    );
    process.exit(2);
  }

  // Validate: assert axonflow-client.ts is the actual source resolved to.
  // If a future contributor moves it, this fails loudly instead of writing
  // a partial baseline (the same trap that snagged us in py SDK regen on
  // a multi-repo dev env — see ADR-047 follow-up notes).
  const clientTs = path.join(__dirname, '..', '..', 'src', 'axonflow-client.ts');
  if (!fs.existsSync(clientTs)) {
    console.error(
      `error: ${clientTs} not found. The wire-shape gate is keyed to this file; if it was moved, update lib.js's CLIENT_TS path.`,
    );
    process.exit(2);
  }

  const interfaces = extractInterfaces();
  const schemas = loadSchemas(specsDir);
  const { drift, unmapped_in_spec } = computeDrift(interfaces, schemas);

  const out = {
    _comment:
      'Baseline of KNOWN wire-shape drift between the OpenClaw plugin\'s wire-bound TS interfaces and the AxonFlow agent OpenAPI spec at openapi_specs_sha. The CI gate fails on drift OUTSIDE this baseline. Entries here should be burned down over time via targeted PRs that either (a) update the plugin interface, (b) update the spec to document the missing fields (file platform-side), or (c) mark the type @sdkDerived if it is a plugin-side derivation that will not live on the wire. Generated by scripts/wire-shape/refresh.js.',
    openapi_specs_sha: sha,
    registered_types: Object.keys(WIRE_BOUND).sort(),
    per_type_drift: Object.fromEntries(
      Object.entries(drift).sort(([a], [b]) => a.localeCompare(b)),
    ),
    unmapped_in_spec: unmapped_in_spec.slice().sort(),
  };

  writeBaseline(out);

  console.log(`Wrote baseline: ${BASELINE_PATH}`);
  console.log(`  openapi_specs_sha: ${sha}`);
  console.log(`  registered_types:  ${Object.keys(WIRE_BOUND).length}`);
  console.log(`  per_type_drift:    ${Object.keys(drift).length}`);
  console.log(`  unmapped_in_spec:  ${unmapped_in_spec.length}`);
}

main();
